# Generated by Django 3.2.6 on 2021-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysEventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=255)),
                ('locale_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('transferred', models.BooleanField()),
            ],
            options={
                'db_table': 'holidays_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'oil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_int', models.IntegerField()),
                ('sales', models.FloatField()),
            ],
            options={
                'db_table': 'sample_submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_nbr', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('cluster', models.IntegerField()),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nbr', models.IntegerField()),
                ('date', models.DateField()),
                ('store_nbr', models.IntegerField()),
                ('family', models.CharField(max_length=255)),
                ('onpromotion', models.FloatField()),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nbr', models.IntegerField()),
                ('date', models.DateField()),
                ('store_nbr', models.IntegerField()),
                ('family', models.CharField(max_length=255)),
                ('sales', models.FloatField()),
                ('onpromotion', models.FloatField()),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_nbr', models.IntegerField()),
                ('transactions', models.IntegerField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
