# Generated by Django 3.2.9 on 2021-11-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211113_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('entry_base', models.CharField(choices=[('Relative Strength Index (RSI)', 'rsi'), ('On Balance Volume (OBV)', 'obv'), ('Moving Average (MA)', 'ma'), ('Bollinger Bands (BB)', 'bb')], max_length=200)),
                ('entry_cross', models.CharField(choices=[('Above', 'above'), ('Below', 'below')], max_length=200)),
                ('entry_target', models.CharField(choices=[('Closing Price', 'closing_price'), ('Volume', 'volume'), ('Level', 'level'), ('BBands (BB)', 'bb'), ('Moving Average (MA)', 'ma')], max_length=200)),
                ('entry_level', models.IntegerField()),
                ('entry_ma_window', models.IntegerField()),
                ('entry_price', models.IntegerField()),
                ('exit_base', models.CharField(choices=[('Relative Strength Index (RSI)', 'rsi'), ('On Balance Volume (OBV)', 'obv'), ('Moving Average (MA)', 'ma'), ('Bollinger Bands (BB)', 'bb')], max_length=200)),
                ('exit_cross', models.CharField(choices=[('Above', 'above'), ('Below', 'below')], max_length=200)),
                ('exit_target', models.CharField(choices=[('Closing Price', 'closing_price'), ('Volume', 'volume'), ('Level', 'level'), ('BBands (BB)', 'bb'), ('Moving Average (MA)', 'ma')], max_length=200)),
                ('exit_level', models.IntegerField()),
                ('exit_ma_window', models.IntegerField()),
                ('exit_price', models.IntegerField()),
                ('init_cash', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('data', models.JSONField()),
                ('song_file', models.FileField(upload_to='songs/')),
                ('midi_file', models.FileField(upload_to='midi/')),
            ],
        ),
        migrations.RemoveField(
            model_name='songs',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.artist'),
        ),
    ]
