# Generated by Django 3.2.9 on 2021-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211128_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='entry_ma_window',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='exit_ma_window',
        ),
        migrations.AlterField(
            model_name='backtest',
            name='entry_base',
            field=models.CharField(choices=[('rsi', 'Relative Strength Index'), ('obv', 'On Balance Volume'), ('ma', 'Moving Average'), ('bb', 'Bollinger Bands')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='entry_cross',
            field=models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='entry_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'Level'), ('bb', 'BBands (BB)'), ('ma', 'Moving Average (MA)')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_base',
            field=models.CharField(choices=[('rsi', 'Relative Strength Index'), ('obv', 'On Balance Volume'), ('ma', 'Moving Average'), ('bb', 'Bollinger Bands')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_cross',
            field=models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'Level'), ('bb', 'BBands (BB)'), ('ma', 'Moving Average (MA)')], max_length=200),
        ),
    ]
