# Generated by Django 3.2.6 on 2021-11-09 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBacktests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_chart', models.FileField(upload_to='')),
                ('backtest_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'backtests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableCharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_chart', models.FileField(upload_to='')),
                ('biz_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'charts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableCurrencyuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'currency_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableForecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_chart', models.FileField(upload_to='')),
                ('forecast_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'forecasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('song_file', models.FileField(upload_to='')),
                ('song_analysis', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
