# Generated by Django 3.2.9 on 2021-12-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211201_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='entry_base',
            field=models.CharField(choices=[('rsi', 'RSI'), ('obv', 'OBV'), ('ma', '200-SMA'), ('bb', 'B-Bands')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='entry_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'Level'), ('bb', 'B-Bands'), ('ma', '200-SMA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_base',
            field=models.CharField(choices=[('rsi', 'RSI'), ('obv', 'OBV'), ('ma', '200-SMA'), ('bb', 'B-Bands')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'Level'), ('bb', 'B-Bands'), ('ma', '200-SMA')], max_length=200),
        ),
    ]
