# Generated by Django 3.2.9 on 2021-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211201_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='entry_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'RSI-Level'), ('bb', 'B-Bands'), ('ma', '200-SMA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exit_target',
            field=models.CharField(choices=[('closing_price', 'Closing Price'), ('volume', 'Volume'), ('level', 'RSI-Level'), ('bb', 'B-Bands'), ('ma', '200-SMA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='init_cash',
            field=models.IntegerField(),
        ),
    ]
